services:
    HanhanChen\UtilitiesBundle\Twig\DayTranslateExtension:
        arguments:
            $translator: '@translator'
        tags: ['twig.extension']

    HanhanChen\UtilitiesBundle\Twig\MonthTranslateExtension:
        arguments:
            $translator: '@translator'
        tags: ['twig.extension']
